apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-git-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/dacofr/hello-appset.git
      revision: main
      files:
      - path: "envs/**/config.json"
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: '{{ path.basename }}'
      source:
        repoURL: https://github.com/dacofr/hello-appset.git
        targetRevision: main
        path: 'charts/noop'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
